---
name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  yamllint:
    uses: networkservicemesh/.github/.github/workflows/yamllint.yaml@main

  build-and-test:
    uses: networkservicemesh/.github/.github/workflows/build-and-test.yaml@main
    with:
      os: '["ubuntu-latest", "macos-latest", "windows-latest"]'

  golangci-lint:
    uses: networkservicemesh/.github/.github/workflows/golangci-lint.yaml@main

  checkgomod:
    uses: networkservicemesh/.github/.github/workflows/checkgomod.yaml@main

  exclude-replace:
    uses: networkservicemesh/.github/.github/workflows/exclude-replace.yaml@main
